######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 5 14:25:14 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
